name: ui_leafguard
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.4.1
  supabase_flutter: ^2.7.0
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  table_calendar: ^3.2.0
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  intl: ^0.20.2
  camera: ^0.11.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/slogan/pepper_slogan.png
    - assets/img/plantes/pink_gerbera.png
    - assets/img/plantes/nest_fern.png
    - assets/img/plantes/young_banana.png
    - assets/img/plantes/dahlia.png
    - assets/img/storyboard_pickImage.jpg
